# Generated by Django 3.0.14 on 2022-05-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appvocado', '0002_auto_20220503_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='closed_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='end_date',
            field=models.DateField(),
        ),
    ]
