# Generated by Django 3.0.14 on 2022-05-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appvocado', '0003_auto_20220503_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id_1', models.IntegerField()),
                ('user_id_2', models.IntegerField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='friends',
            constraint=models.UniqueConstraint(fields=('user_id_1', 'user_id_2'), name='unique_friends'),
        ),
    ]
