# Generated by Django 3.0.14 on 2022-05-03 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appvocado', '0004_auto_20220503_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteOffers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appvocado.Offer')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='favoriteoffers',
            constraint=models.UniqueConstraint(fields=('user_id', 'offer_id'), name='unique_favorite_offer'),
        ),
    ]
